name: k6 Performance Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run k6 Local Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-test.js

      - name: Upload k6 Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary-report
          path: summary.html
          retention-days: 1
